/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Arbol;

import javax.swing.JOptionPane;

/**
 *
 * @author toshib
 */
public class VentanaRegistro extends javax.swing.JFrame {

    /**
     * Creates new form VentanaRegistro
     */
    public VentanaRegistro() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JTextField();
        jButtonAgregarUsuario = new javax.swing.JButton();
        cedulaUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(40, 1, 75));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cedula:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 140, 60, 22);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 90, 70, 22);
        jPanel1.add(nombreUsuario);
        nombreUsuario.setBounds(180, 90, 180, 30);

        jButtonAgregarUsuario.setBackground(new java.awt.Color(40, 1, 75));
        jButtonAgregarUsuario.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonAgregarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregarUsuario.setText("Agregar");
        jButtonAgregarUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAgregarUsuario);
        jButtonAgregarUsuario.setBounds(210, 210, 120, 40);
        jPanel1.add(cedulaUsuario);
        cedulaUsuario.setBounds(180, 140, 180, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarUsuarioActionPerformed
        if (nombreUsuario.getText().isEmpty() | cedulaUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campos vacios");
        } else {
            String nombre = nombreUsuario.getText();
            int cedula = Integer.parseInt(cedulaUsuario.getText());
            Arbol.getInstance().insertar(cedula, nombre);
            System.out.println("Recorrido del árbol creado \n ");
            Arbol.getInstance().preOrden();
            if (Arbol.getInstance().isEncontrado()) {
                JOptionPane.showMessageDialog(null, nombre + " Usuario no agregado");
                Arbol.getInstance().setEncontrado(false);
            } else {
                JOptionPane.showMessageDialog(null, nombre + " agregado exitosamente");
                Arbol.getInstance().setEncontrado(false);
            }
        }
    }//GEN-LAST:event_jButtonAgregarUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cedulaUsuario;
    private javax.swing.JButton jButtonAgregarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreUsuario;
    // End of variables declaration//GEN-END:variables
}
