/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Arbol;

import javax.swing.JOptionPane;

/**
 *
 * @author toshib
 */
public class VentanaRegistro extends javax.swing.JFrame {

    /**
     * Creates new form VentanaRegistro
     */
    public VentanaRegistro() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cedulaUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JTextField();
        jButtonAgregarUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(cedulaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 119, 29));

        jLabel1.setText("Cedula:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 101, 29));

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 101, 29));
        getContentPane().add(nombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 119, 29));

        jButtonAgregarUsuario.setText("Agregar");
        jButtonAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 92, 35));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarUsuarioActionPerformed
        if(nombreUsuario.getText().isEmpty() | cedulaUsuario.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Campos vacios");
        }
        else {
            String nombre = nombreUsuario.getText();
            int cedula = Integer.parseInt(cedulaUsuario.getText());
            Arbol.getInstance().insertar(cedula,nombre);
            System.out.println("Recorrido del árbol creado \n ");
            Arbol.getInstance().preOrden();
            //VentanaInicio ven = new VentanaInicio();
            //ven.setVisible(true);
            
            
        }
    }//GEN-LAST:event_jButtonAgregarUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cedulaUsuario;
    private javax.swing.JButton jButtonAgregarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nombreUsuario;
    // End of variables declaration//GEN-END:variables
}
